# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:ZdYySfrK5Am7I+n8+H8vmKzXytsyzWRZatnp9l0C568jj1IDGOnn53UIg/ftC3foyctRHmzzts8govuKtwb5JTxNRA1dtgXR065Jkl3e8Qm+HIj8mzWUMjDTauE59rFzoZhjvB6oQNWRFV84aMGD2TI9KfSeg6qO2vMzn2wMZMRUAx5D3EFBekH0kyrS1hALKYbtH9hzp2nwJHD4C3gyNqvCUgknuECjCz4Mfo4caQ==,iv:xn0S90WIOUslWtIxr2o934xEuNaHB9/d5vrLejLeRzg=,tag:atB3hV2di+CDvLWXTpnHaA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbjQza0ExbEE0eXdaR1dB
        cGFmdkxkQzJqdzdvakFpd3V4UzNNR0E0MUQ4CnNmVzJsOUtLWlp4a1N4TmgvNm83
        aUc3TXM0UmhtMkFBNHMrV3R3OU9XZXcKLS0tIGVXZFpmNXQ4RGs1eENuc2tkVDdE
        WWV3bW1XVWVZSitvSENmaGhiWklxcEUKSJiMRd3Ys+Yv9rpFgc1wg3XMe2l8Zbmd
        YvzqvRDPOcLAIIvWFNo5Yp1cUPASIJ/qOkEW2/h5V8YQucn/yNiYaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T01:59:11Z"
  mac: ENC[AES256_GCM,data:quKBMjfh32T6HKvcw7cvnvY51twBGgh9TQCRDxQUE1TMVjuJO8hTOpNealglvIuctfr1Kc39GSq2IBdesER9S0wDXNqER+LCshqbKXpLR0JPIqoyyTuUzqkG75BHW237vtvbulAJ4x+fU/Cl2H/F4VhtNjZnl5pqNUwwR1Vbzb8=,iv:Wgg2hdw9SmUwnYygeH8hgnaSWqS2CmhxEE9oNYUs3Dw=,tag:98PPiFi5he88S1WT6l7q0g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
