# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:WSU6LPwApYJ3mTcYlcE1LYKW6zYG6t9AEr22SIaFlWNYU9iezAQC0caTEdlU2tmyY6AzXwIOezTMRnfgn73yNXAK41e6irJQyOtg5KaVmn8/tK9CjH7RvbI3+7IT84X8gOJS214JmfStGxZD3wkVVCgBi08ELVwQdioDNiKU1hPh0erlQ37hWh7T/T34lXHqQlLXJ4HDQfe6gKsOwcADp6MFAxZwYrhX4pTumWoqfg==,iv:J6Sy2B1MbCICq14C23fs4v1Kbff+nkv5Cl6T/myp5PY=,tag:xLlNIFyrS/Hqi6MffL4d3g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcFhEaEJjb2N6YTFFbjBH
        U05vM2htbTR0ZldPV0lJZjAxSnVxMWdMb0Q0CkRsM2cwWGFtbTlDREVzYzFUaTRs
        b0E3SDBpVTlaMWxibTM2aVRmRWk5bGcKLS0tIEZYYUlhd1VkOCtBNnpWeWhlTUtJ
        cTRKL09keS9XaEJUaXhhMlo5ZXc2S0UK4t92M2ZoctXRCDWOBTxaIWE4/Tjk9EI3
        ELzVZBjGL6jXMCGf5Mu2x4ObKkWoltWxPa1CJqXYNPCN/vboOuEz9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T03:07:34Z"
  mac: ENC[AES256_GCM,data:+u78tU621KNzoYSsfzP1ayQbWhOp+xZonWFkNthGwfIk79B+OFUWba46HYgFfjsJPO8chydPvOXc9Hs2s4WFhPHp25teef289b2xVmP6MZoF+DdtCvTEMNU5tRN4qgCNX7GSvURLYh/EiuG/csGUcmLweBOBaKsy/rhEo9dDSwg=,iv:9u9cz8wwwsDhtHkoumaR3vDB1es1lopzsvvhDOWPGmk=,tag:IDdGLllgsFgikXPxgscnMw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
