# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:M1RrxnGJG3Q6+W1QxoHz28XlzJ39HKvdvT1ECtHsxQb7ViB3D0JU3B43tGFvHnvLBeFL4Kgz7QozQS74u8NxYFzzRHCN1nbIR+D+L2HDS9tW+6OVVNvhibHtroAy1qoghpWcBUgBK9JUSo+ZTbPxlkIJor1N7ErRv+fL6EUlPoFHtuzIQDLS/nGFpfR2d8nFs9ELwUmvnhYQPU/xnFglmTc0BolLMeBvt3HTUFB3+g==,iv:b7mDSj5kCAYJyR0NKU/Pc6U6pgKzYfea/i9xS7Fs6/c=,tag:d5uMZ3sNKfM81K5UucuqTg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSmEycFlUc1FnVStXTTBL
        Q1dKNEMrQXZOaStNUUNqZDNXOTY4UmE1NFZRCmRDVlBTUDhQSDMzQm5YOWhETWJ6
        M2NvK0I1bm5tOFBBeDd3TFZjSXlXZ00KLS0tIHRhQi9yTkNWMHZ6bmtnTVdCbjBC
        SVpZRWFPRXpuV08zaFF3Tk96Qk40ZjAK0tUDojuH9idx/Pq+NbsKQ95HWKVcblUn
        MvsnJKXTcCvWE5qKOIhaWzA8JblOfNl+zOWoufMkUnLX4tykhM5THg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T00:49:12Z"
  mac: ENC[AES256_GCM,data:BrAqq29G20S3Lm/pJ1ctlKd5rV9Pq/ibszKLBdW4uujiFjHFju/aCyzoZvRKT5InQZTW07P4s/hotES+okNBf5MrrfuSgqUUwZgNXxZ/BCXdCF10i+bq5lMruhvQrheMiuo8IP7bZyjGDeQcpMO5AP1AMuAL3bJIxukwS9KU7ak=,iv:TQHB6y8sHcE1xeqFMsEfwW4XPE7VYdsCPRxVucBgy20=,tag:xEQVdGsBMWiUFIYMvH1uQg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
