---
creation_rules:
  - path_regex: kubernetes/.+\.sops\.yaml
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    key_groups:
      - age:
          - age1dlsaw4anajxrwmyr6r23uwluvj49ph8zlwrnrds2pw4lvvgcuc5qjy9zek
stores:
  yaml:
    indent: 2
