# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:uKiLBCgqFea5KKU8aMcDxw3aZRhLWcc/N4XTca3UpNXu6P0Sk17osA==,iv:LnVvkUS/6UIgfhs7urkE55iJLlGe9NHtXtOf5LzI7rI=,tag:CljcXoRjn3g5EYfgfWq5Fg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eGdiWmZHOVJ6eEtoWVpK
        a2xUQUdEQjJWVnIrcmFKMEpKcGtKZ0wybDNNClZYS1k3VkhoSWJsWi9Gamk0Q3gv
        R2lEOXhtcGxlSTkwSVMzalZ1cnIrY3MKLS0tIFNOTXEycVBjT3Y0bDNMalpvWlN6
        TjliR2NWK2hQVHZTTVM2YUphQ2FKZjAKcoUkEqejDt0efJcqSPiD/IrKzcHZsKSn
        upcIT55n1LOcn645hQ0qKj9fUrHipSjTBmLtPEhLi1xaj7jM3i+u1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T01:59:12Z"
  mac: ENC[AES256_GCM,data:SHQfb84NBbUjDX+qYHX0McDWwXusq6cBe4/0ixWdM4p/dTOUGG4mucrVlGl0yvTiTxS7MonbRz4RICtac8kRKMToZRc0AoodKm+KC1G0yeEWag3e2/PiHzTyhb6yL3Qnw/3QeqDtjoIsKxkJVUNSxbpXu39W/ZLd4rwAl8/P+pQ=,iv:D4bsTaGHXo87/ds3eN1u7QeA1ZOcEto4cFevKrJU6Lo=,tag:ntwU1TdLn80rD5xkoq3iMQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
