# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:PGeYddbov/2A6bSXGRWiCE4wQ9ROjW2zqhTqsa413Mxyeu7X53+B/w==,iv:LAmJ4z8loqMbG+r0gVIZ/bJ2PFbQsYWcYHaPmbyrWVM=,tag:XkQA24SP8+eWNBKRpUkGjg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBib0ltTkpTaU1GL3FyRlRm
        ZWlwOVBwS1J4VncrS1FZS1I1M2RYMFZiU1R3Cmx6R3dLL0MzcnNQL0U2TGtzTFhs
        ckJwOWdXMVZRQ1hSa0V5cU40b3NUUFkKLS0tIGMzQmVXdFRnZHptdGxMbnB1Y0xm
        MldNcUZ2eFBVR2JCcjhxc0pib3VEN2MKylNnY6uz/aZjPMUgMn8XzldqbFMN5Ocr
        O45V1OxoMfr6Bxep1WLlDYJ4m5l39wcsNZA6nExP7rdtQ5NAbYl3UQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T04:48:48Z"
  mac: ENC[AES256_GCM,data:yfbyXY2eyYkMhmMOFwGnTaYIOXXLz2BVF7sKXuHUDR5HG9MBxtY0J71P5U1qGM+YFq4aQXObQpYhKx5+3u6E5MUqm+UNvGFIhpJ+IUGRqp79uVIZkiTR6hYb0SzBIhkjJMoZUaBpE9OjOc8LhbgzU28bfBtCp5TnjUpI6tEtzns=,iv:jW9LqqTcv6gv3d6WsD5NWUvtRgKFeAEiZmS19bmtg2U=,tag:LJZu0X/44YBpxwSoW4Hvug==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
