# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:gALHZp6GiLFolofcFQBgtVqHyNZD8G9lPhoqujU8CVz8rw4qBEzhNw==,iv:ReL8I4t3UROnXfDVvN7KXjyhiQAu4gW1sUYDpJUCFLE=,tag:PLD+txtlY7uxUHVyd76ijw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZU0g5eXpCUWtzWC9nN0lh
        OU5RbEFKaHBndG5BWTVXYUJrMzlKdzJSeGpFCm0ydDFIaVZ4ZWs0dHVzNmJVbnN6
        eTY2a0x3NUs3ZjJzbEhPRE5zQ29vN1kKLS0tIDlBZmNYdlZoNzN5V09zaTd1cXAw
        YXFVNmhwbG9XT0RqM1MzTE42TzRYQmMK9wBHrZTOGEIjX9Eir8NF5Abe/jyk5+7H
        XLCWo+jagoF3wTjz/zfgzZskkN5vkH1BBR9FPhcutDj1xSe0ofcrgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T04:01:20Z"
  mac: ENC[AES256_GCM,data:XIqUoOWVA4So8rD0yi3HIryPUx4MDK4BExK0+/RUgYqQqLORAfcffntjBnDv67ZUB+d1x+OZx9UPtjmtksOIaOH80QC/J5PgsZXFwkPjPNDcqaPQrsXEKsnLGo/3spukQuoiUM1EUCEh4YauncmumFkAFHtRxDrX1LGW5IgP0M8=,iv:dxYLmRphWpxffvwaBoWfHjQ2PeHZvx55H3KOgWMFCo0=,tag:b0IjQ01VyABd1sghDyOxMg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
