# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ofaYm0+InrilnrAqy0zmgci5Y7D664NkkY2ThLmlIRk=,iv:/xM5ZGK7lYa+5iCebIDYh3nBNdIQTkVvQUqVPbCN4yA=,tag:dEQcSgFjRdt0lrBYlBxXhg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbTltQWtOaUpzNmI0ZFQ0
        Q0g5Z3VtYjl4VjdxN0pvSGxqREQxbHNNSkVvCkZETS9qUXVtTTZqeDRKdi9ZRTFm
        MWhjWUtjZkZ2M2huUlN0TmlES0xoakEKLS0tIDZxZEJrS2JTYVpQTmRkZFJFVUNH
        bGtjVGhzTGM3NmRMczZyUGtHTG1PV28K4YnlZZ6Y3W/sQk6vyneY8w6JiqQ0VOF9
        ONKhIsqg3E/LZ98aSkiMH+fb+UHZCzDqv+e86xrCIGqRy+PDxaAang==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T04:48:48Z"
  mac: ENC[AES256_GCM,data:C2xPHmVgWo2VopV8CSblQnkwHHgDCgTRHkWNPeFxx12vfRPi9UMTuMMSoRolnq3EShFQjRBPw0HxyaaMPNMsR33qGIyRgYHFyr488ycviANJhiHHs4ebI1PBVN2tUP3F2+TRrZ8iIo2blVEYB+qFu4hL0qHNVK2SoAY6vYaj5p4=,iv:JHJcMae3KUmC89Viip2Ov3gYMUSk4HA4g+l87E9okDg=,tag:fU4D7IqSDOuPDlV07JJ8Tw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
