# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:yM1NC7y9a7YaVFUP68NJtRs+lM5e3Rk/qwbSRubHOno=,iv:RdUb9gajWZ1050NHbi3ezK2tyuS1BvwHKbq/xsin9io=,tag:KzSLj+rqepw4jiLixn9TDQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVVpDUzFVV0FPekxyeVg0
        bVdCR2ZGTVZxeUloSmpsc3Jia0F5N0d0ZFFvCmFyTVFKQ3MxbFdia1gxazdVc3ZE
        dHpZUWhSaFlWdng1K0F4YXJNRTJGS0EKLS0tIFg5S0hya0NVVnpHYkx0NUdNUXBU
        NmtZWFF1cUd3L1Q0SXlJcVhMZ2w2ZjAK5qlYQKNNT496oC1JZqlD5ArwoNABoohU
        KyyyUyjLl8Uo1Xvwdxd770CauK+syyEcZyRxBlqSMF/QFd89/wQKMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T04:01:20Z"
  mac: ENC[AES256_GCM,data:/0o3C8jSdf1MOA3LFAGbAVY2NFNFzhNUSCx2tbqQLkk3cyslztW/DqKi6RfW3U0E79EfrFCfO5Frgqi4K7CxgrVOWFtpyjkNeGJq24iudCASwk1dJOklAJBvaUcC2n9rrYClDZJj0bSuT2klipV0wyl7E2LPlhHMFypq39uftvA=,iv:NxTvhY1mywvpp8uzCN1HKP1YvVSfD2NQoTdIImxPP/Y=,tag:Shpw4tC8A8IdAqQCa1oeVA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
