# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:EUZwGUJhjFMX+tXQ6X7LtyDWs6dYrR0v1JDgU/Fz8ho=,iv:w8NzdWjree2v+CkCTr4+Ct2YVfV8h/Pfb0pn6R3hw2s=,tag:KP7bgNtozS6knW/6YG55Ug==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUXZDQ3N2YmpTTkszNStl
        V2YxbWIyS2N3Ym56dlB5WTFIT1FDUHFHRXhBClU0WnkwMW5IcVUrUml6dlkwZWZ0
        WUVqeEpnWDNHTnpyL2lXdkwxaTA4ZmcKLS0tIEYzeXY5REl6MllmanRVOUgxZUIr
        bmhYKzVZbEJiWGdmZ0pBeEEvWGpDencKd83Qrv5VAtnWS+MdsrAh48M1v/ZEoGUH
        9Se58L278PFpy7WHlcVPqfHblEI7b7mduUSdECJP0H5LW2Gq51EIiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T00:49:11Z"
  mac: ENC[AES256_GCM,data:HShwLzMhnbf9HKx3Wnj/txXHKhYsOGv3LQtSXUoh9K2IOVAscYf8hReJTJBsDTcw6jif5FzcHP0UvyxIPbieXBVsKRrIUW0qDnjHqvMy79s8udq9p459vqctSjGHtZPspJjaBmeB/4nY4pKjlRMK88CN4sKDVzndUbN+YE3v12g=,iv:BHI1yx1MNGFrzTg/z2lsnhGernb1VyX4uZtLj2jTNTE=,tag:WHAtENM8KXp/vTd0h4flBQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
