apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:UCDotSxbHX6LJCxT1A==,iv:ftXTw3lv2/9YYM/aLAq8nnlJMyU23mkxW9Gvx/O5qIw=,tag:QiyCLOWN9G+Lw7vL27k7Hg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bHZ6VnoxOFZDbmkwSTI2
        dEdKVHBCRG9CaFlIcC9RSjVTdGhJeXZweUJZCkMwdlljbGkra2VjRzFsQjJ5QzFE
        azYxL1p6dFp6K2Zma2lwTi8vVTFPbFUKLS0tIFBjenlsaUV0b21pTisyaW1JcndB
        cDBNQU5iblJ0SklodnY3NFQ5MC9lRjQKts4ohKm4bT7EE3Skb6BOp770HOXCsslf
        zBjlxSwSUK5d6aSQ/UnMqYx+NTDcfA4DusUQkQm8cMzVPrhw46o4hQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T04:01:20Z"
  mac: ENC[AES256_GCM,data:hEWE6eYVdzVDENesQFKdCufYy2kISk8Xii58dfaf1dA8/iYHnyajmXh07AjBIYtRS4Pydq9d4IuqPGTYODTrISKKQklJRYJf8vLXIM69wDEGsvn7v80j8T7nTt5kMYKLp8E6Fgwg6uexJlvQwEPAuC6oLsmTRFpESoki0CKzHUM=,iv:WA3jSoWzGV7PPZ7Y7Q0egq1OUoEpzRjp7XDk2tKYzkg=,tag:I27b/DQ02rN4HXOx5d8Bnw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
