apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ueUfGu8j3CWD0YZ+Jg==,iv:u/I0bkSzWhe0OdQlaEhiDDGn7JjxJUB04z3Ru8C39I8=,tag:+ChhlI15RDmZWd+wkcvUTw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd3BTWHA1TndrV2M1WDVZ
        dnp4RnU1THdDendCc3ZtRnByWS9XYzVhcFFJCmJQZlVqbG41QllSVkM0WXhGM2l2
        OXlMMUM3bGhTMFJpMkJabmJZaWVmMzAKLS0tIG5NYVJXUm5wdzd6N3kzSkJpSi9i
        OXhrS2FBVkxCVStrbExZZFdyMHQvejgKPctmJYJGYIsa3U4NIROkcxAJnLfYCCCI
        q26haGkWbs+aUrerIaaHL1B1WT/Xn7g1J/l4AbTFXveDGt8uqG2qcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T03:07:35Z"
  mac: ENC[AES256_GCM,data:JMYTKEaT3rQLCT67Tk/85T/dnrwXynT1+BoSb75VThRI89W8niPUZIrhMuVR7Blz2/fx69SXq36vQvjEsJ25G39Zi16vSJcPnxRqzNMQf772f9Io1tz8RV7UEdNrwgHqQ+FrTO2P4HmGyK0n01YgyUZbRYwITD9Y52og75Nu6Vg=,iv:ppAfV0X/fCu3LkPGCXBY5+f9wr/sTTfRMRBSwDJ9+vo=,tag:WrZ64RcoA3ogVsgp04A3QA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
