apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:5h/VVMYn+uHfZ54Lzw==,iv:b1PUzGjQr5+kmBSNFUY+DnYf9wKAcmNLl80h97+v5Qo=,tag:ujZDdXw0h66daulzgjcSWg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcFhaeXcyUkZXRjk5QTFr
        RzNnbWtqZ3lMSjlLL202cys1a296MlVWQVcwCmUvblpDZkpHNlRlVDVuT25OaXk3
        dGxDVzJCczlYM29SVXRqV1g3aEhacGcKLS0tIDZWVU5kMUlXKzVMS0pPTGNOVEdV
        dlE2U1U5cjd5c016OEk1Q3V6QUx5VGsKrR3OHoF6H2uMeEYI3uYAYaglbh/9iXru
        Tpsf4XYlKqIGiz7i8HN0tCrhuoGdg5VBkX8MUZzmwadS7aObF0PXSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T04:48:48Z"
  mac: ENC[AES256_GCM,data:Tcf0HD0fmsIXOF90sXmuj6FhWkvHWqWUVg2essijeh/LYk0UlW7tqVSV2SISxSg194+yLEEUCkq266rMkgX9TGZeRp0KUr9JJbXKsFNSlOFvqQI4eKhadF/3kuGEwfiCgx1JEHQjuS7zOODwofY5/So8C0NGXSGm6+kaZd3Nd+E=,iv:jfKCZqIBwdRADM273k+efSvdMBOSVSRsaRlgswsVdOE=,tag:2pBX/lLU/acpycnPvD304g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
