apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:evO7WE35+nxA/tWs/UXO41qHUO5DB2mTXwMz52C7IsDSrRnSmpg3sz6CoWqXjPgny63JrO0mkeuovnIrcwNIO9XkNQaoJ6sLHo0=,iv:EJcT6zs+x54qj4rCrio4qsHROg342Std8P4Pcso3fWY=,tag:fzfpudFm9z28fofrOTv1Fg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMFJsYjBxdUlMQkJuUDQ2
        NGw3cEp2aU9sVFNZa0tpZk1ka0RxK0h3aEVnCit3bFFOL0hLaURzTmVkSmY1eUd1
        M0dZaDV6Q2hNZDVZVEFoTVJ3M094ZUUKLS0tIHVlNnFKMzVNVjVOcWNZRHRBaVhK
        QkpUSXFpbUthMy9nVGhjTEQ2cVRmSFUKdquGsrH63drwFItN7NDuq4EakND8T/Ia
        wP6/LXyWd6R5KGSFMCoKnX0VfTCsYYMm8Rc+LLZB+RwYUep0yNGyuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T04:48:48Z"
  mac: ENC[AES256_GCM,data:7B1T1gunfaKPCkNKufFoPSHCfYU3/0o5JciY+q7N8j/hFbZ8nt9VwPQC6QgYD1jAYuH4eGjmAJqwXjbZqHVkWAIOJGzjvRWDzIneIeLQR4O0kANvbRSt6WHaR87vakOTgfeAcFDzZuWI2U3qn2TUUMmGgmnWZnjouN2aLqlnqSg=,iv:4uHkiMmNuh6BBGCL/HsUE1xDNp3OntNCRR+NU4BRnHI=,tag:4tTz+Kg8ou0msKU27gNEnQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
