# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:u0Gb2Ao6XFidgLZAqcyy4RCv+za004JMb1QMQuyqLhHUQzFXx4iNDQ==,iv:UtavWrnWPdAxyTOvV++gkZqpnqIMvs8VxyHAT45oZfY=,tag:rgJSZKZtJ3iSAP/dllqdjQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSkpncENhMmtGMW5qdXdl
        VWVkUGlrL1NVZHZKRk5xTzNtU0tpR285eXljCjA0UitPWDJGejdKV0w2S2dCNE5L
        UlRYbmZ6NDVnalBBNVZkN01tS0h5b2sKLS0tIEVKREJLN0w1cjBMZkxTcTIvUDZq
        WlhrYTdiY2xBM1VaQWU5blJEQ0tkY1UK8L/2vq9+Flr7vYZuHV1npWH/mCa1HLYP
        /aTcOn+5AkNNzl02dtxayJgrqthk1yTNVEl0o9oH41UNpEbA5WzX/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T04:25:16Z"
  mac: ENC[AES256_GCM,data:4qo1XbPjzz2HV1UrWRvPmlBjepc8OTa3Gqm6gi2LDGMUGrMlDTeaT9zu80f9me2+lxFKaAk6BwDC8UOZuJAGzA5843nLhis6Ya0vRy+gIyq55zyw5WwLo0cgHTOGgNk+A0xY2lpPXwRZGXBf3BDN3EyjyrVCEtLgAp7fn3ZUEys=,iv:9vMwMtJ1p1dkL1b9SAvsBDSOOwIK+chx6Qd953jBBwk=,tag:JiudHW2tGuNYZa/jTcSL5g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
