# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:4KApN3ACalQvrSALYEGZ5Sz0wobfHMSMbSaVinRd8NE3XR7J3Qdudw==,iv:N0sbypHkjvC7o7npzdqrGsAZep3uUq6Ec4JbN8kv7+A=,tag:8hcq3+Lwgfce4DGsbaceNg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUHFXc2Q5bzc5N21mTmh6
        MUZHN0NPaTgvcVB0NWlwWFRPaVVyWmFoQUYwCnN1TTFiZjI4bEoyTmVUL053TGxL
        dkhNNGRxYmV1aXFWNW9iS3A4SFlrNWsKLS0tIFhEbVJyNmdKUzU4c1RzZFhzNDdT
        eTBBVWRqUlhWWkxPVU1HZnFKZ045dFUKWBnsB9kMCkQ+/LQnDb4ohPSYt73IbJOJ
        SNYsDYaE422vPyWB+n+Yvmdtswa/b7+ZcUkb5+Dr/hOViD6r2KdXlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T03:07:35Z"
  mac: ENC[AES256_GCM,data:CdnXpUa3tQHJfwwbRY84668wquRa+huX96O0N+nK0wGv7gV6VHXvdLiJ0onoExWu6UADmSjd3UQLVnF93OgSPPTuSEPkorhyyldBz0+1IxErOHYS5hdYEwJFS/QdYNKkFYbb0sh0UTNYXXGCKewFZiNSrWs57zzAq+NohEMSb84=,iv:OwIxzN31qPsHsakyArCvo+kEuUdyWVcj+Hjc7kJbd7g=,tag:Lbg7C7vNCIURjPya46uxJw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
