# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Q/xK06JM3sjXb1GG4FNmOIkUPI7sADplPfv2xYkLimDzdI3se4MFRQ==,iv:1JIxEHI3k6R+0dzDwDWsIOUtAOtDhb+7BjIWfD7mMOk=,tag:azWlMujFcAi10LTt+YzaMg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uwnfas74u4nsnjkhzwj2hva0nyx7tn9g5w3l7zpq6lqz5q7zkexqq4wr2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OVFnUWo2aVhLVzFyajV6
        dWtTbk1mK3RlYlVURTNvTFBnamMrSXdlTmd3Cjk0cC9LNkdlN2VXcThLeWNqTy81
        YmY2THlSYWg3aWNWdFRudW1GUmdValUKLS0tIERwVDc4OVZvTGVScXNCb0NQQUpX
        elU4L2MyYnRjVWx1WjZlZ0REeHZ0Zk0KRZQet4s59/RSzcK+2KoRn/havG4aURXR
        dFfdfKvTSvTI9ITgXZP62oL5e/nYFTu0LHblB6Eel2UNQFdjBqTG7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T04:01:20Z"
  mac: ENC[AES256_GCM,data:qvMBxVRHIrclbbiV+Zu91j/WL9ga+NFjVL9vc3RqS8annbiKW1Rt414zIs1jUwpILAzfEdfQ3ZxNeMTgOTgCbd+QT+5sJ82EoO4iNfCgE4X1YZE3/RJVHMZW6k4M0LOu8yXvWhsjMhkf5Jit8+fgyhWWlnBkUgYL1KKYm+6BYJA=,iv:Gr0IZfednFFtxLJHmS7IQt0PgNtybkrLQc98pCasQLM=,tag:572nDmiJnFMipScEEw5Lzg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
